name: Scrape
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: Scrape
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm run start 145

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: api
          folder: data
