name: Scrape
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install project dependencies
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm ci

      - name: Scrape reservations
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm run start 145

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: data
