name: Scrape
on:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install project dependencies
        run: npm ci
      - name: Scrape reservations
        run: npm run start 145
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: data
